[package]
name = "clipboard"
version = "0.1.0"
authors = ["wotmshuaisi <wotmshuaisi@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0.8"
futures = "0.1.29"
listenfd = "0.3.3"
serde = "1.0.102"